language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
before_script:
  - python manage.py migrate
script:
  - python manage.py test
  - coverage run tests.py
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master