language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install -U pytest
  - pip install pytest-django
before_script:
  - mysql -u root -e 'CREATE DATABASE djangorest;'
  - mysql -u root -e "CREATE USER 'djangorest'@'localhost' IDENTIFIED BY 'djangorest';"
  - mysql -u root -e "GRANT ALL ON djangorest.* TO 'djangorest'@'localhost';"
  - mysql -u root -e "GRANT ALL ON test_djangorest.* TO 'djangorest'@'localhost';"
  - python manage.py migrate
script:
  - python manage.py test
  - pytest currencyapp/tests.py
  - coverage run --source='.' manage.py test
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
services:
  - mysql